


spring.application.name=corso2spring



# File txt dove i conti vengono salvati e intervallo di salvataggio (ms)
conti.file=conti.txt
conti.salvataggio-ms=10000


# Swagger UI: /swagger-ui.html - documento JSON: /v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
